[workspace]
members = [
  ".",
  "herb-config",
  "herb-highlighter",
  "herb-printer"
]

[package]
name = "herb"
version = "0.10.3"
edition = "2021"
authors = ["Marco Roth <marco.roth@intergga.ch>"]
description = "Rust bindings for Herb"
readme = "README.md"
license = "MIT"
repository = "https://github.com/marcoroth/herb"
keywords = ["erb", "html", "html+erb", "ruby", "rails"]
categories = ["parser-implementations", "development-tools"]
include = [
  "src/**/*",
  "vendor/**/*.c",
  "vendor/**/*.h",
  "build.rs",
  "Cargo.toml",
  "README.md"
]

[lib]
name = "herb"
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "herb-rust"
path = "src/main.rs"
required-features = ["cli"]

[features]
default = ["prism"]
color = ["dep:colored"]
cli = ["color"]
prism = []

[dependencies]
colored = { version = "3", optional = true }

[dev-dependencies]
colored = "3"
insta = "1.40"
cargo-insta = "1.43.2"

[build-dependencies]
cc = "1.0"
glob = "0.3"
bindgen = "0.72"
